# Generated by Django 4.2.6 on 2023-10-19 18:31

import apps.skif.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=300, unique=True, upload_to=apps.skif.models.user_directory_path, verbose_name='фото')),
            ],
        ),
        migrations.CreateModel(
            name='UserImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='SkierDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_insert', models.DateTimeField(auto_now_add=True, verbose_name='дата внесения пробежки')),
                ('day_select', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], db_index=True, default=19, verbose_name='день пробега')),
                ('day_distance', models.FloatField(db_index=True, help_text='введите в формате 10,23', verbose_name='дистанция за пробежку')),
                ('day_time', models.TimeField(db_index=True, help_text='введите в формате 00:00:00', verbose_name='введите время пробежки')),
                ('day_average_temp', models.TimeField(db_index=True, help_text='введите в формате 00:00:00', verbose_name='средний темп')),
                ('calory', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Потрачено калорий')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skif.image')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to='accounts.profile', verbose_name='участник')),
                ('skirun_dislike', models.ManyToManyField(blank=True, related_name='skirun_disliked', to=settings.AUTH_USER_MODEL)),
                ('skirun_like', models.ManyToManyField(blank=True, related_name='skirun_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ежедневный забег',
                'verbose_name_plural': 'пробеги по дням',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
                ('for_skier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='KeyWordClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='кодовое слово')),
                ('kwteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teams', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'Ключевые слова',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=350, verbose_name='Текст комментария')),
                ('comment_pubdate', models.DateTimeField(verbose_name='Дата публикации')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='skif.skierday')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
